---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u6621605/public_html/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp -R .htrouter.php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
