<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width,initial-scale=1'>

	<title>Pateron</title>

	<link rel='icon' type='image/png' href='/favicon.png'>
	<link rel='stylesheet' href='/global.css'>
	<link rel='stylesheet' href='/build/bundle.css'>

	<script defer src='/build/bundle.js'></script>

	<!-- BULMA CSS -->
	<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.css'>
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

	<!-- FONTS -->
	<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Lato&display=swap" rel="stylesheet">
	
</head>

<body>
<input id='csrf' type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
	value='<?php echo $this->security->getToken() ?>'/>
</body>
</html>
